### ISSUE TITLE
auth_path error in tests

### ISSUE THREAD

**Issue by ldodds** [kartta-labs/editor-website#18]
I'm trying to follow steps to setup this app. When running the tests I get a number of errors, the most common one is a complaint that `auth_path` is not defined, e.g:

```
Error:
ReportDiaryEntryTest#test_it_works:
ActionView::Template::Error: undefined method `auth_path' for #<#<Class:0x000055c42aa04008>:0x000055c427d697c8>
Did you mean?  about_path
               audio_path
    app/views/users/login.html.erb:18:in `_app_views_users_login_html_erb___1619390377688783283_47150508548920'
    config/initializers/cors.rb:9:in `call'
    config/initializers/compressed_requests.rb:27:in `call'
```

I'm not clear where this helper is defined, I assume one of the dependencies. Any pointers to which library this is from or where the issue might be?

Thanks.

**Comment by rkversion** [comment]
Please ignore test errors for now, we have not yet updated the tests: they are as we inherited them, i.e., may be referencing code that was deleted, and not testing newly added code.

**Comment by ldodds** [comment]
OK thanks.

The reason I started exploring this is that after firing up the application it forced me to a login page and a redirect loop. So it looked like something may have been wrong with login. But I'll investigate further and try to find the cause of the problem.
